import FeatureCard from "./FeatureCard";

import {
    FaFileAlt,
    FaRobot,
    FaChartLine,
    FaBuilding,
    FaFilePdf,
    FaBrain,
} from "react-icons/fa";

const features = [

    {
        icon: <FaFileAlt />,
        title: "Resume Analysis",
        description:
            "Upload your resume and let AI analyze your strengths and improvement areas.",
    },

    {
        icon: <FaRobot />,
        title: "AI Mock Interview",
        description:
            "Practice real interview questions generated by Gemini AI.",
    },

    {
        icon: <FaBuilding />,
        title: "Company Specific",
        description:
            "Prepare for Amazon, Google, Microsoft, TCS and many more.",
    },

    {
        icon: <FaChartLine />,
        title: "Performance Report",
        description:
            "Receive detailed AI feedback with score and improvement suggestions.",
    },

    {
        icon: <FaFilePdf />,
        title: "PDF Report",
        description:
            "Download your complete interview report anytime.",
    },

    {
        icon: <FaBrain />,
        title: "Gemini Powered",
        description:
            "Powered by Google's Gemini AI for smarter interview preparation.",
    },

];

function Features() {

    return (

        <section
            id="features"
            className="py-24 bg-gray-50"
        >

            <div className="max-w-7xl mx-auto px-6">

                <div className="text-center mb-16">

                    <h2 className="text-5xl font-bold">

                        Why Choose

                        <span className="text-blue-600">

                            {" "}AI Resume Interviewer

                        </span>

                    </h2>

                    <p className="text-gray-600 mt-6 text-lg">

                        Everything you need to prepare for your dream job.

                    </p>

                </div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">

                    {
                        features.map((feature, index) => (

                            <FeatureCard

                                key={index}

                                icon={feature.icon}

                                title={feature.title}

                                description={feature.description}

                            />

                        ))
                    }

                </div>

            </div>

        </section>

    );

}

export default Features;