spring:
  application:
    name: ai-resume-interviewer

  datasource:
    url: jdbc:mysql://localhost:3306/ai_resume_interviewer
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000
file:
  upload-dir: C:/uploads